export default {
  canvas: {
    format: 'image/png',
    quality: 0.92,
    width: '',
    height: '',
  },
  startZoom: 1,
  imgPosition: {
    top: 0,
    left: 0,
    width: '',
    height: '',
  },
  floors: {
    gf: {
      layers: [
        {
          name: '0',
          src: '../../public/floorplans/unit/GF/0.png',
          opacity: 1,
          top: 0,
          left: 0,
          width: '',
          height: '',
          zIndex: 0,
        },
        {
          name: '1',
          src: '../../public/floorplans/unit/GF/1.png',
          opacity: 1,
          top: 0,
          left: 0,
          width: 123,
          height: 456,
          zIndex: 1,
        },
      ],
      groupOpacity: 1,
      top: '',
      left: '',
      width: '',
      height: '',
    },
    ff: {
      layers: [
        {
          name: '0',
          src: '../../public/floorplans/unit/FF/0.png',
          opacity: 1,
          top: '',
          left: '',
          width: '',
          height: '',
          zIndex: '',
        },
        {
          name: '1',
          src: '../../public/floorplans/unit/FF/1.png',
          opacity: 1,
          top: '',
          left: '',
          width: '',
          height: '',
          zIndex: '',
        },
      ],
      groupOpacity: 1,
      top: '',
      left: '',
      width: '',
      height: '',
    },
    rf: {
      layers: [
        {
          name: '0',
          src: '../../public/floorplans/unit/RF/0.png',
          opacity: 1,
          top: '',
          left: '',
          width: '',
          height: '',
          zIndex: '',
        },
        {
          name: '1',
          src: '../../public/floorplans/unit/RF/1.png',
          opacity: 1,
          top: '',
          left: '',
          width: '',
          height: '',
          zIndex: '',
        },
      ],
      groupOpacity: 1,
      top: '',
      left: '',
      width: '',
      height: '',
    },
  },
};
